### ISSUE TITLE
Intraday chart not displaying all data

### ISSUE THREAD

**Issue by Pietvw** [BitMEX/ninjatrader-bitmex#12]
Hi

I receive an error on my data feed when I connect (see attahced).

I also see gaps in data when loading intraday charts. Some days are completely missing, see date axis. (image attached)

Regards,
Pieter
![error](https://user-images.githubusercontent.com/36691869/36468951-1ec926da-16ee-11e8-8474-3657f4595046.png)
![xbtusd](https://user-images.githubusercontent.com/36691869/36468965-28021748-16ee-11e8-9423-abc5c98b7fe9.PNG)

**Comment by ryanfox** [comment]
What dates did you specify when creating the chart?

**Comment by Pietvw** [comment]
Hi Ryan

It was set to 50 days.

Regards,
Pieter

**Comment by ryanfox** [comment]
That error should be fixed in [v1.0.6.](https://github.com/BitMEX/ninjatrader-bitmex/releases/tag/v1.0.6)

**Comment by Pietvw** [comment]
Hi Ryan

Thanks, the I/O operations error is now fixed, but the charts still don't load all the data. See this one below, even after reload all historical data it has a big gap between Jan and Feb.

Regards,
Pieter
![xbt](https://user-images.githubusercontent.com/36691869/36777496-55808676-1c72-11e8-9938-cfde7e755cda.png)

**Comment by FargoMoney** [comment]
Charts still dont load all data, I have the same exact problem.

**Comment by ryanfox** [comment]
It's currently a limitation of the API limiting the maximum time span that can be queried at once. If you limit the date range to 8 days at a time, it should return that full data set.

**Comment by FargoMoney** [comment]
Still does not work, I literally uninstalled ninja and back multiple times.. and redid the whole process a couple time, limit to 8 days and my price still shows that bitcoin is @ 10.6..... its missing so much data I don't know what to do anymore. Sorry for my rant, but I did everything over and over again, no solution........

**Comment by ryanfox** [comment]
You might need to reload your historical data (right click on chart -> reload). I can't reproduce the bug when requesting intervals of 8 days' worth or less.
